name: "python release"
on:
  release:
    types:
      - published
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: deps
        run: python -m pip install -U build

      - name: build
        run: python -m build

      - name: publish
        # gh-action-pypi-publish uses TWINE_PASSWORD automatically
        
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
           username: __token__
           password: ${{ secrets.PYPI_TOKEN }}
      
